### ISSUE TITLE
missing [active]domains in clean.list

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#16]
@funilrys  here is a link(s) for reference(this is how i found out) but i remember i've notice that  some domains were missing in the past but didn't think of it too much at the time. It's a kind of  a concern.Let's hope that you'll be able to trace the issue:
https://github.com/anudeepND/blacklist/issues/31#issuecomment-455934119
https://github.com/anudeepND/blacklist/issues/31#issuecomment-455951655
https://github.com/anudeepND/blacklist/issues/31#issuecomment-455955142

P.S. Actually i found it in [INACTIVE](https://github.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server/blob/master/output/hosts/INACTIVE/hosts) and that domain is very much alive so i'm thinking now that there is a bug with how the domains are considered active/inactive.

**Comment by funilrys** [comment]
Hi @dnmTX please report to https://pyfunceble.readthedocs.io/en/latest/columns.html#doubleclick-net.

**Comment by dnmTX** [comment]
Reported :point_up:

**Comment by funilrys** [comment]
@dnmTX I meant: look at the documentation :joy_cat: 

I had a good time with Mitch trying to optimize the process when we started (Around January 2017). We constated that all 404 domains for *.doubleclick.net where inactive so we put them as `INACTIVE` until the status code changes to something which is not 404 :smile_cat: 

We really do more than WHOIS and NSLOOKUP :wink:

**Comment by dnmTX** [comment]
My bad(kind of embarrassed right now). I'll remove the issue. Still....
...don't you think that showing 404 on such a domains is kind of suspicious to say the least?
Probably it's a good idea to make some exception on those as they really need to remain blocked.

**Comment by funilrys** [comment]
Closing as clarified.

Also: That beahavior can be disabled by maintainers at @dead-hosts. @mitchellkrogza decided that it's still good to keep it here.

**Comment by funilrys** [comment]
Something is coming (soon) around this @dnmTX :smile_cat:

**Comment by dnmTX** [comment]
I'll believe it when i see it 👀

**Comment by funilrys** [comment]
Partial code is fast ready to ship will become complete code after next stable release of PyFunceble + modification of the administration file :wink:

**Comment by funilrys** [comment]
* Correction: The code is ready as exeprimental and should not be considered as experimental anymore from the next release of PyFunceble.

**Comment by funilrys** [comment]
Oups wrong ping in commit :sob: I need to sleep :joy: catch you later @dnmTX.

Sorry for the noise @dmTX ...

**Comment by funilrys** [comment]
Closing as it is now implemented.

**Comment by dnmTX** [comment]
🙌 ALL HAIL THE NEW `VOLATILE.LIST` 🙌
