### ISSUE TITLE
[Feedback] Week 10 of 2019: Monday, March 4 – Sunday, March 10, 20

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/dev-center#18]
Hello there, 

please report here every infrastructure issues (suspected or confirmed) of this week (Monday, February 25 – Sunday, March 3, 2019).

Issue that implies big changes are welcome as a new issue!

Cheers,
Nissar

**Comment by funilrys** [comment]
A complete restart (from A to Z) of all the infrastructure will be executed around midnight (Berlin Time) as mentionned per https://github.com/Ultimate-Hosts-Blacklist/dev-center/issues/14#issuecomment-469052268.

**Comment by funilrys** [comment]
Restart started.

**Comment by funilrys** [comment]
Restart finished.

**Comment by dnmTX** [comment]
Reporting:
According to [travis-ci](https://travis-ci.org/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended) filtering was done 2 Hrs ago but the [front page](https://github.com/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended) still not updating.
@funilrys  you really need to take closer look at this,looks like the problem with updating the lists on the front page is still very much present.

**Comment by funilrys** [comment]
@dnmTX Thanks for giving me a point of start. Just restarted it to see if it is isolated. If it is the same output, I'll look at it more deeply.

**Comment by funilrys** [comment]
A restart did the trick but I think that a complete review/rethink/rewrite of the autocontinue subsystem is needed. Will start to work on that asap.

**Comment by funilrys** [comment]
Because: The previous endeed with xxx and the restart started at tttt something is wrong :thinking:

**Comment by dnmTX** [comment]
@funilrys meanwhile if you don't mind(whenever you have time of course) restarting it once in a while so i'll be able to fetch updated lists instead of the same ones over and over again. On my end it's automated to fetch them weekly(mon,tues,wedn). 
Crossing fingers that you'll be able to fix this soon as it seems to be most annoying issue so far.

**Comment by funilrys** [comment]
@dnmTX Once we are stable enough they will be restarted almost automatically (or at least within 2 hours) once they finished  :smile_cat:

**Comment by funilrys** [comment]
Restart started because of latest release of PyFunceble which was tested at https://travis-ci.org/Ultimate-Hosts-Blacklist/repository-structure/builds/503719864.

**Comment by funilrys** [comment]
Restart finished.

**Comment by dnmTX** [comment]
@funilrys  some builds are [failing](https://travis-ci.org/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended).Can you please take a look.Thank you.

**Comment by funilrys** [comment]
Sorry was AFK to get some rest. 
The URL you mentionned was because of a possible Network downtime from Travis CI. Indeed it PyFunceble was not even started. It was during the configuration of the working Environment.

Cheers,
Nissar
