### ISSUE TITLE
New lists to add

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#20]
@funilrys  looks like a good addition to the rest of the lists here. 
Both are updated regularly with not that many duplicates against other lists that i'm using(that sounded kind of selfish,but it's more like "in general"). 
If you decide to add them see if you can place them in the same repo together(not sure if it's possible so it's a suggestion for now). 
Thank you 👍 

AdServers:
https://www.squidblacklist.org/downloads/dg-ads.acl

Malware:
https://www.squidblacklist.org/downloads/dg-malicious.acl

**Comment by funilrys** [comment]
Hi @dnmTX, can you put them into the comparison system (https://github.com/Ultimate-Hosts-Blacklist/dev-center/tree/compare-with-system) ?

Create 2 PR to the `compare-with-system` branch were you edit `info.json` I will see if they are okay to be included ! :smile_cat: 

Thanks again for everything.

Cheers,
Nissar

**Comment by dnmTX** [comment]
@funilrys ok,i'll do that next week as it's not urgent. I'll fork that repo and create 2 PR's for you.
Thank you for taking the time to take care of the other issues from the past week 👍

**Comment by dnmTX** [comment]
@funilrys  i wonder if we better wait to add them based on #23. The [Malware](https://www.squidblacklist.org/downloads/dg-malicious.acl) list is huge(90,000+ entries).
Maybe down the road after you fix the problem or.....?

**Comment by funilrys** [comment]
@dnmTX, 
We can compare it today and keep the PR open so that we can see the amount that are not present into our infrastructure by there  by simply closing/reopening it :+1:

**Comment by dnmTX** [comment]
DONE.....i think 🤔
