### ISSUE TITLE
[Feedback] Week 17 of 2019: Monday, April 22 – Sunday, April 28, 2019

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/dev-center#31]
Hello, World!

Please report here every infrastructure/build/test issues (suspected or confirmed) of this week.

**Week covered by this issue:** Monday, April 22 – Sunday, April 28, 2019

**Note:** Issue that implies big changes or not related to infrastructure or build/test are welcome as a new issue!

Cheers,
Nissar

**Comment by funilrys** [comment]
@dnmTX If you have time can you take a look at https://github.com/Ultimate-Hosts-Blacklist/repository-structure/tree/dev I need feedback about the outputed/generated files. 

Indeed I made some drastical changes and I want to be sure that it does not break things for people like you who merge/use the outputed files.

It is still testing `www.shellalist.de` but it will be finished soon as the system test around `15500` for every builds (about 16 minutes running time).

Cheers,
Nissar

**Comment by funilrys** [comment]
Okay just discovered an issue 🙂 Take your time as I have to fix the issue with the auto continue subsystem :wink:

**Comment by dnmTX** [comment]
@funilrys  i'm not really sure what to look for.On the surface it looks good,first line is populated on all lists,other then that i need something specific.I saw in `clean.list` there are IP numbers mixed with domains,i'm guessing this is just for the test.I guess we have to wait until you push this everywhere so i can start testing and observing then.I'm pretty sure that there will be some bugs and that's ok. As long as you fix them as soon as i report them i think will be fine.

**Comment by dnmTX** [comment]
Ok,so here is the thing with `shallalist.de` in particular(i don't use it and never paid attention until now).It's a compressed list of many lists inside and some of them comes with mixed IP's and domains together(which is weird to say the least).And you know that it's not gonna work.So for those lists you need to see if it's possible to somehow separate the IP's from the domains i guess or anything you can figure out to make it work.

**Comment by dnmTX** [comment]
@funilrys  i've notice that some domains from the [CoinBlockerList](https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists) with some weird characters in the front got filtered and removed,in particular [this one](https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists/blob/42fda2308a516f9c447da056f3629e94acf78ef0/domains.list#L341),which is pretty much alive and harmfull:
![Capture](https://user-images.githubusercontent.com/34774426/56852468-761c3080-68e1-11e9-8f09-e1014dced118.PNG)

I know you might say rules and all but when it comes to mining i don't think whoever(sick brain) does that will follow any rules.If you don't mind make some exceptions as those domains really need to remain blocked.
Thank you 👍

**Comment by funilrys** [comment]
Hi @dnmTX, It should (already) be fixed into the next updater. I'm actually busy but will try to do my best to release the next one soon.

For the rest, I'll try to take the time to read and answer later this day.

Thanks for your understanding.

Cheers,
Nissar

**Comment by dnmTX** [comment]
@funilrys  take your time.Filtering is working as intended and the above suggestions are not priority,it's just  that you asked and i started throwing everything that i can think of 😄 .
Thank you for fixing the "weird character" issue. 👍

**Comment by funilrys** [comment]
@dnmTX Let me know when you did a copy of all files you use. I'll deploy the new tool after that :wink:

**Comment by dnmTX** [comment]
@funilrys  i'm good on my end,next fetching is scheduled Mon. through Wednesday  next week so deploy away 😄

**Comment by funilrys** [comment]
I'm preparing the central repository.

**Comment by dnmTX** [comment]
:crossed_fingers :crossed_fingers :crossed_fingers

**Comment by funilrys** [comment]
Central repository updated. All other repositories are going to sync with it from now.

**Comment by funilrys** [comment]
Starting the complete restart (from the beginning) of all input sources repositories.

**Comment by dnmTX** [comment]
@funilrys  if you want you can open a new FEEDBACK issue and close this one so not to mix up any old and new issues. 
I'll be monitoring and let you know if anything.

**Comment by funilrys** [comment]
Restart (from the beginning) of all input sources repositories finished.

Please report all infrastructure issue in the coming days at #32.
