### ISSUE TITLE
Add xorcan/hosts

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/dev-center#34]
@xorcan [said](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/515):

> take a look.
> 
> https://github.com/xorcan/hosts
> https://github.com/xorcan/hosts/blob/master/xhosts.txt
> https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt

**Comment by funilrys** [comment]
Test result: https://github.com/Ultimate-Hosts-Blacklist/dev-center/pull/35#issuecomment-505622811

**Comment by dnmTX** [comment]
@funilrys looking at the lists it's very much focused on Turkish websites.If you ask me not too many will benefit from it,just doesn't worth it but it's up to you.

**Comment by xorcan** [comment]
the list also includes dangerous, pishing websites that are not even in other lists. of course it's up to you :)

**Comment by mitchellkrogza** [comment]
For the global scale of Ultimate Hosts I give this a +1 for inclusion

**Comment by dnmTX** [comment]
@xorcan nothing personal,regarding my comment above.It's just my opinion on the matter. 😉

**Comment by smed79** [comment]
@xorcan 

1. 
> the list also includes dangerous, pishing websites

I would recommend you to categorize/comment blocked domains in your list (ads, tracking, pishing ...), so that it's will be more clearer for the user.

2. 
Are you sure of blocking `cdn.jsdelivr.net`, `code.createjs.com`, `res.cloudinary.com` 
and the `.edu.tr` tld ?

3. 
> 127.0.0.1 109.73.75.29
> 127.0.0.1 109.73.75.3
> ...

You can't use the hosts file for mapping one ip address to another ip address.

4. 
It is recommended using `0.0.0.0` instead of `127.0.0.1` (see https://git.io/fjKfN)

**Comment by dnmTX** [comment]
Spot on @smed79 . I guess i was too tired when i checked the list to miss all that ☝️

**Comment by funilrys** [comment]
@xorcan Any update/comments on @smed79 point?

**Comment by xorcan** [comment]
list updated based on suggestions
@funilrys @smed79

**Comment by funilrys** [comment]
Great @xorcan will schedule the creation for next week.

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/xorcan_tuerk_ad_list

**Comment by dnmTX** [comment]
@funilrys you need to remove this list from here. By the look of it,the maintainer @xorcan has no longer presense here in GitHUB along with his repo and the blocklist. Also most of the latest reported false-positives are from his list which gets me concerned.
Reopening this,close it when done. Thank you 👍

**Comment by funilrys** [comment]
✅ 
✅
