### ISSUE TITLE
[Feedback] Week 40 of 2019: Monday, September 30 – Sunday, October 6, 2019

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/dev-center#38]
Hello, World!

Please report here every infrastructure/build/test issues (suspected or confirmed) of this week.

**Week covered by this issue:** Monday, September 30 – Sunday, October 6, 2019

**Note:** Issue that implies big changes or not related to infrastructure or builds/tests are welcome as a new issue!

Cheers,
Nissar

**Comment by dnmTX** [comment]
@funilrys the lists are not updating...again(6 days since the last update).Please check when you have time.Thank you!

**Comment by funilrys** [comment]
Hi @dnmTX, thanks for the info. I will try to look into it before the end of the week.

Cheers,
Nissar

**Comment by funilrys** [comment]
Restart (of last part) launched.

**Comment by funilrys** [comment]
Restart (of last part) finished.

**Comment by funilrys** [comment]
Monitoring will handle the restart of the newly failed in the coming hour. It's mainly because of a recent patch that was quickly fixed.

Time to sleep, 
Thanks for everything!
Catch up later!!

Cheers.

**Comment by funilrys** [comment]
P.S: I didn't have much time to deeply look into all repos. But for the few I looked that far, the data didn't change. But I can't assume that it's the case everywhere, so I have to look at everything which was made the last 10 days (out of the outage in the last 24 hours) everywhere.

**Comment by dnmTX** [comment]
I'll keep an close eye on the one i'm using and if it's still the same will let you know.
Thanks @funilrys  👍

**Comment by dnmTX** [comment]
@funilrys  it's still not fixed. Out of seven repos that i'm monitoring/using only two got updated,on the rest Travis Cl says it passed but no lists got updated which is not normal.[This one](https://travis-ci.org/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers) errored since you last restarted.

**Comment by funilrys** [comment]
Canceled all builds.

**Comment by funilrys** [comment]
Started launch (from the beginning) of all input test.

**Comment by funilrys** [comment]
Finished launch (from the beginning) of all input test.

**Comment by dnmTX** [comment]
I'll be 👀
