### ISSUE TITLE
Is there a project-blacklist?

### ISSUE THREAD

**Issue by Somebodyisnobody** [Ultimate-Hosts-Blacklist/dev-center#40]
Hey together,
is there an internal source for the Blacklist, where I can request to blacklist domains or do I need to contact the external sources?

**Comment by dnmTX** [comment]
Hi @Somebodyisnobody  all the lists here are third party managed so,yes,you need to contact them directly. There is a small exception though,one of the owners here maintains his [own list](https://github.com/mitchellkrogza/Badd-Boyz-Hosts) so i guess you can start with him.
**PING** @mitchellkrogza

**Comment by dnmTX** [comment]
Closing as the issue was moved to Bad-Boyz 👍

**Comment by funilrys** [comment]
@dnmTX just send a comment with `/move to owner/repo_name` :+1:

**Comment by dnmTX** [comment]
Got it. Thanks @funilrys  👍
