### ISSUE TITLE
A more aggressive whitelist list ?

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/dev-center#45]
I [said](https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/107#issuecomment-589964030): 

I have to get my finger into the DNS server after I fixed the central repository but we could create a more aggressive whitelist list for such cases (later of course) 🤔

Your opinion?

**Comment by smed79** [comment]
I prefer to be more specific for each case.

Who use the lists hosted on our repo should check what the list includes and what it will block before using it, especially when she is dedicated to block specific content.

So, it will have no sense to use "[facebook](https://github.com/Ultimate-Hosts-Blacklist/smed79_blocklist_facebook)" or [nsfw](https://github.com/Ultimate-Hosts-Blacklist/smed79_blacklist_nsfw) list then say i don't have access to **FB** or [PH](https://git.io/JvuJC) !!

**Comment by funilrys** [comment]
@dnmTX @smed79 True, I forgot we have a `data` directory for some specific whitelist which anybody can fetch and use with our whitelisting tool.

As an example, Facebook one https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/master/data/facebook

We should probably do more promotion of them in the future.

**Comment by funilrys** [comment]
But actually I could fetch the data whitelist lists into the DNS server later. Thanks for reminding me about that @smed79 :-)

**Comment by funilrys** [comment]
And yes, it's probably time to clarify a bit the central README :thinking:

**Comment by dnmTX** [comment]
Guys,the issue with the **nsfw** list is that it's included in the Ultimate-Hosts.. and whoever uses it ending up with PornHub being broken.I'm guessing @smed79 would like all of his lists here so they can be filtered from dead domains(nothing wrong with that),aggressive list simply(in my opinion) will not work(still wondering how it would be applied and in which lists and we have regular whitelist and so on and so on...)
I can think of only one solution, @funilrys to figure out a way all the present lists that are on rotation for filtering to remain there but not all of them to be offered in the Ultimate-Hosts... or the feature DNS service.This way any agressive(extra) lists will be excluded and there will be minimal complains from users.

**Comment by dnmTX** [comment]
> @dnmTX @smed79 True, I forgot we have a data directory for some specific whitelist which anybody can fetch and use with our whitelisting tool.

I didn't even know about them. Are those included in the main whitelist or are just extra if needed?

**Comment by dnmTX** [comment]
@funilrys  any thoughts on what i suggested above ☝️? Reason i'm asking,and i don't mean to rush you or something but we still have open [whitelisting request pending](https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/107)  which is very relevant to the discussion here.

**Comment by funilrys** [comment]
@dnmTX, I agree that we need to be more flexible in the future. And that's in one of my todo-list. As I mentioned previously, in the future when our backend will be stable enough (code side), I will spend a big amount of time working on the API and the web app in order to let people choose what they want. Imagine it as a list compilator for their specific needs. 
In fact, we already have a database that is updated daily. We only need to make use of the available data. But that takes a bit of time because there is a lot to take into consideration and I don't know if @mitchellkrogza's server can handle the amount of request we might get.

About NSFW, the problem is that removing it goes against @mitchellkrogza description in the central repository:
> The Ultimate Unified Hosts file for protecting your network, computer, smartphones and Wi-Fi devices against millions of bad web sites. Protect your children and family from gaining access to bad web sites and protect your devices and pc from being infected with Malware or Ransomware.

The `Protect your children` side might be problematic. Unfortunately, we can change everything else in the infrastructure but for that repository description, @mitchellkrogza has to take action.

So the question is actually where are we going? You (@dnmTX & @smed79) and I can make and take all decisions and necessary changes about that. But on the other side, @mitchellkrogza has to approve the little part about the central repository description.

What can we do for/with that NSFW case?
* One thing is sure, the DNS will have all the content of the `data` directory implemented in it in order to reduce users' noise.
* We can temporarily remove the NSFW repository from the central repository by adding it to this list in the configuration of the updater: https://github.com/Ultimate-Hosts-Blacklist/dev-center/blob/8065ae97f59e85f7a374719a0c2d4b47c6a6b970/ultimate_hosts_blacklist/central_repo_updater/configuration.py#L82-L89
* We can leave it as it is and create an `nsfw` or `pornhub` file inside the `data` directory with what needed to be whitelisted and then redirect the end-user to the whitelisting tool and the file to use for that case. I'm talking about the following: 
    * https://pypi.org/project/ultimate-hosts-blacklist-whitelist/ ==> Whitelisting tool
    * https://github.com/Ultimate-Hosts-Blacklist/whitelist/tree/master/data ==> Complementary which can be given through the `-w` argument of the whitelisting tool.

As you can see, almost everything is ready as I planned some of those cases in the long term. 
It's just up to us to make a temporary decision now @dnmTX  @smed79, and a definitive decision in the future one we can propose a tool for end-user to compile their own list. :smile_cat: 

Cheers!

**Comment by smed79** [comment]
@funilrys The best solution in this case is to completely ignore  the NSFW repository.

**Comment by dnmTX** [comment]
> @funilrys The best solution in this case is to completely ignore the nsfw repository.
I recommend also to ignore facebook repo.

I second that.This is the way to go for those two lists 👍

**Comment by funilrys** [comment]
Applied. With a bit of luck, it will also be in the central repository with the next update (in a few minutes).

As I mentioned we just remove them from the central repository. Not from the infrastructure.

**Comment by dnmTX** [comment]
@p1r473  this ☝️  should solve the issues you have with PornHub. 
We will still need you to confirm though. Update your lists,test it and report please so i can close your issue in the whitelist repo.

**Comment by p1r473** [comment]
All good now, thanks!

**Comment by p1r473** [comment]
> @p1r473 this ☝️ should solve the issues you have with PornHub.
> We will still need you to confirm though. Update your lists,test it and report please so i can close your issue in the whitelist repo.

This was really fun homework ;)

**Comment by smed79** [comment]
@funilrys 

"_**Airelles_Anti_Sex_Hosts**_" repo should also ignored as what you did for the nsfw list.

**Comment by dnmTX** [comment]
> "Airelles_Anti_Sex_Hosts" repo should also ignored as what you did for the nsfw list.

This is also related to one of our newest [whitelist requests]("Airelles_Anti_Sex_Hosts" repo should also ignored as what you did for the nsfw list.)

**Comment by funilrys** [comment]
@dnmTX @smed79 We (@mitchellkrogza  and I) decided to completely delete "Airelles_Anti_Sex_Hosts" from our infrastructure. 

I just deleted it.

**Comment by mitchellkrogza** [comment]
:tada: long overdue, that must have felt good :grin:
