### ISSUE TITLE
MaxMind blocked

### ISSUE THREAD

**Issue by alexwasserman** [Ultimate-Hosts-Blacklist/dev-center#47]
Hey guys,

Sorry if this is the wrong place to report it - but, seems odd for us to block MaxMind? It's a legit commercial tool/service, nothing spammy.

I use pfSense at home and both the Suricata (IDS), and pfBlockerNG (IP/ DNS blocking) tools come with built-in functionality to consume the MaxMind DB as do other commercial services.

Can we whitelist?

Thanks,

Alex

**Comment by dnmTX** [comment]
`/move to https://github.com/Ultimate-Hosts-Blacklist/whitelist`
