### ISSUE TITLE
[Feedback] Friday, May 29, 2020-....

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#48]
Hello, World!

Please report here every infrastructure/build/test issues (suspected or confirmed).

Note: Issue that implies big changes or not related to infrastructure or builds/tests are welcome as a new issue!

Cheers!

**Comment by dnmTX** [comment]
@funilrys  just reporting my observations so far:

On ALL repo lists only the `volatile.list` is updated after filtering is done. 
The `whitelisted.list` and `clean.list` are not.

[THIS ONE](https://github.com/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended) continue failing and not updating,even after your last attempt to fix it.
Probably needs a deeper look(i'm using it and it's important to me as it is one of the most active lists here)

That's it so far...i'll keep observing.I know you are busy so whenever you can.Thank you 👍 
Stay **SAFE** and **HEALTHY** 👈

**Comment by funilrys** [comment]
@dnmTX Thanks for this! I noticed that Travis CI changed/added endpoints that are not implemented by that monitoring system. I will try to fix that asap. It's just that right now, there is a lot going on privately along with professionally. 

Thanks for everything @dnmTX.

Stay safe and healthy too.

**Comment by funilrys** [comment]
Just for the record.
We added the `xxx.allover.co.za` domain into https://github.com/Ultimate-Hosts-Blacklist/blacklist/blob/master/domains.list.

Therefore, this domain will be used for the internal tests in order to know if the list was injected correctly into the DNS Server. 
We control that domain.

**Comment by funilrys** [comment]
Just for the record.

Our mirror and apps may be unreachable on 07.08.2020 between 07:00 and 23:00 (Berlin Time). We are moving the server to another distribution.

Stay safe and healthy
Nissar

**Comment by funilrys** [comment]
Just for the record.

It's now completed.

**Comment by funilrys** [comment]
Just for the record. 
I just stopped the monitoring system.
I just stopped the job started.

From now, the test will restart themselves every 24 hours until I rewrote it in order to stop and automatically report a new issue when something is going wrong.
