### ISSUE TITLE
[Maintenance] *.json files removal due to stalled filtering

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#52]
**REFERENCE to myself**

> This may be a problem in our infrastructure. We should probably completely clean those repositories if they really are not into upstream.
> 
> For the record (if I'm not around):
> To clean everything, delete all `*.json` file (BUT NOT `info.json`) and delete `output/continue.json`.

**Comment by dnmTX** [comment]
@funilrys  will start with [one repo only](https://github.com/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended) so not to get you overwhelmed and if success will continue onward.
Will wait on your feedback and further instructions 👍

**Comment by funilrys** [comment]
Ongoing work regarding #54. Closing.
