### ISSUE TITLE
[spam404] URL change request for better filtering

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#9]
@funilrys  the current [URL](https://raw.githubusercontent.com/Dawsey21/Lists/master/adblock-list.txt) is fetching the lists designed for AdBlock Plus and there are domains that don't make it to the [domain.list](https://github.com/Ultimate-Hosts-Blacklist/Spam404/blob/master/domains.list) to be filtered which are pretty much active
( top portion,everything with `##[href^=....`). Changing the URL to:
https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt  will include those missing domains and therefore will provide better protection.

**Comment by funilrys** [comment]
Hi @dnmTX,

Actually we used the AdBlock because It was the historicaly linked file and PyFunceble can decode them :smile_cat: 

As mentioned previously, created an issue under PyFunceble in order to track this issue.

Cheers,
Nissar

**Comment by dnmTX** [comment]
@funilrys  thanks for looking in to it.For me it doesn't really matter which lists is fetched as long as all the domains are included.I'm using `spam404` in my AdBlocker but seeing how many domains are already dead/inactive(4000+) i'd prefer to download the lists from here(filtered) and remove it from my AdBlocker(too much dead weight).I'll wait until gets fixed though.

**Comment by funilrys** [comment]
DShield.org ==> https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List/commit/93e1504d86758eb94e64b1e0baa710620c987275 

cameleon ==> Still waiting for Travis CI ==> https://travis-ci.org/Ultimate-Hosts-Blacklist/cameleon_at_sysctl.org/builds
